
[env:esp32dev]
platform = espressif32@^6.5.0
board = esp32dev
framework = arduino

upload_port = COM5

lib_deps=
    https://github.com/adafruit/DHT-sensor-library
    https://github.com/fdebrabander/arduino-liquidcrystal-i2c-library
    https://github.com/adafruit/rtclib
    https://github.com/adafruit/Adafruit_BusIO
